feat(lang): add support for Traditional Chinese
enitimeago/make-it-mmd pull request #68
Opened 2024-06-27 08:27 UTC by yelandiealma

2024-06-29 13:29 UTC, enitimeago requested changes
Thank you very much for the contribution!

Before I merge can you undo the change in line 1 of Localization.cs? I think there is a BOM character that should not be removed.

2024-06-29 13:29 UTC, enitimeago commented on Packages/enitimeago.non-destructive-mmd/Editor/Localization.cs
> -﻿using System.Linq;
Sorry I think my lint GitHub Action was not working correctly, could you revert this change?

2024-06-29 15:09 UTC, yelandiealma commented
Is it okay?

2024-07-03 15:49 UTC, enitimeago approved these changes
LGTM, thank you!

2024-07-03 15:50 UTC, merged

2024-07-03 17:16 UTC, enitimeago commented
This is now live as version 1.1.0-beta.3, thanks again!

2024-07-03 17:16 UTC, enitimeago commented
@yelandiealma This is now live as version 1.1.0-beta.3, thanks again!